### ISSUE TITLE
SWIM invoicing needs to access PO number from Campaign overview tab using python to check which campaign is missing po number

### ISSUE THREAD

**Issue by vma4Subsea** [4Subsea/fourinsight-campaigns-python#26]
Need PO number from overview tab to be included in campaign.general()
![image](https://user-images.githubusercontent.com/19995040/200258705-7d987021-5e25-43ea-bae2-7adcefae2ec8.png)
Thank you <3

**Comment by heidi-holm-4ss** [comment]
DST-337
